### ISSUE TITLE
is date ranges the only field that can be estimated

### ISSUE THREAD

**Issue by jsoohoo2** [AdobeDocs/analytics-2.0-apis#320]
Issue in /src/pages/guides/endpoints/data-repair/server-call-estimate.md

Cab we make a note whether estimations can include conditions?

**Comment by joshua-harrison-2011** [comment]
Hi @jsoohoo2 

When you say "conditions", are you referring to `filter` criteria added to the Data Repair job?  Assuming this is what you mean, we don't support conditions on the Server Call Estimate endpoint because the API bills on rows scanned, not rows matched/changed.  If we supported conditions, it could significantly underestimate the cost for a job.
