### ISSUE TITLE
medium(referral/organic/ppc/email)

### ISSUE THREAD

**Issue by EwainCai** [AdobeDocs/analytics-2.0-apis#377]
Is it possible to use AA 2.0 APIs to separate data from different medium(referral/organic/ppc/email) like GA, I can't find any examples in the development documentation.

  Thanks.

**Comment by gigazelle** [comment]
Couple questions.

* Can you elaborate what you mean by "separate"? Would this simply be in a reporting capacity?
* The [Marketing Channel](https://experienceleague.adobe.com/docs/analytics/components/dimensions/marketing-channel.html) dimension collects roughly the equivalent of GA's medium, but it does require configuration (setting up marketing channel processing rules) in order to correctly collect data.

I'd also recommend checking out [this page](https://experienceleague.adobe.com/docs/analytics/technotes/ga-to-aa/reports/acquisition-reports.html), which explains rough approximations between GA reports and Adobe Analytics reports.

**Comment by EwainCai** [comment]
@gigazelle 
I found it, thanks for your help.
